# Generated by Django 3.1.4 on 2021-01-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souko', '0002_auto_20210108_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='completed',
        ),
    ]
